name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile

    - name: Run build
      run: pnpm build
      env:
        NEXT_PUBLIC_VIBES_ENGINEERING_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_VIBES_ENGINEERING_PROJECT_ID || 'dummy-project-id' }}
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'https://dummy.supabase.co' }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'dummy-anon-key' }}
        VIBES_ENGINEERING_NOTIFICATION_BACKEND_ENDPOINT: ${{ secrets.VIBES_ENGINEERING_NOTIFICATION_BACKEND_ENDPOINT || 'https://dummy-endpoint.com' }}

    - name: Run lint
      run: pnpm lint